### ISSUE TITLE
Service Accounts disabled randomly 

### ISSUE THREAD

**Issue by rtloeffler** [Armory/armory#12]
Axene Health Partners

*Version*
Armory: 1.10.207
fiat_version: 0.36.0
lighthouse_version: 8addc87

*Feature Area*

Pipeline

*Description*
Added Service Account to Front50 as described [here](https://www.spinnaker.io/setup/security/authorization/service-accounts/) and added service role to spinnaker.yml

Expected: Add Automated trigger in configuration stage of pipeline. When clicking on Run As User have the user populate there.

Actual: Runs fine for awhile, then randomly the "user" will disappear from the Run As User dropdown. 
![screen shot 2018-02-08 at 1 12 34 pm](https://user-images.githubusercontent.com/8787209/35999187-d6b445ce-0cd3-11e8-94c9-30f1eede7ac6.png)

*Steps to Reproduce*

Not sure whats causing the problem so i dont have a way to reproduce. Will update if i can. 

*Additional Details*
the only way i got it to work again after disappearing was to "re-add" the service account to front50 with a new name and then update that name in the spinnaker-local.yml file, restart spinnaker and then all previous service accounts would populate (including the ones that disappeared). _very odd_

**Comment by kevinawoo** [comment]
Fixed!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

# Causes:
- The service account was a member of `admin` but the user was a member of `admins` (typo)

**Comment by dotdotdotpaul** [comment]
Fixed by moving to HA with a persistent Redis.
